### ISSUE TITLE
gSender-1.0.2-arm64.AppImage can not run

### ISSUE THREAD

**Issue by barabuti** [Sienci-Labs/gsender#75]
I use raspberry pi 4 64bit version.
I usually work by cncjs.
I try to use your gSender-1.0.2-arm64.AppImage.
But it can not run.
By terminal show
pi@raspberrypi:~/Downloads $ ./gSender-1.0.2-arm64.AppImage
08:36:46.159 › Error: /tmp/.mount_gSendedEMyvJ/resources/app/node_modules/@serialport/bindings/build/Release/bindings.node: cannot open shared object file: No such file or directory
    at process.func [as dlopen] (electron/js2c/asar.js:140:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1196:18)
    at Object.func [as .node] (electron/js2c/asar.js:140:31)
    at Module.load (internal/modules/cjs/loader.js:981:32)
    at Module._load (internal/modules/cjs/loader.js:881:14)
    at Function.Module._load (electron/js2c/asar.js:779:28)
    at Module.require (internal/modules/cjs/loader.js:1023:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at bindings (/tmp/.mount_gSendedEMyvJ/resources/app/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/tmp/.mount_gSendedEMyvJ/resources/app/node_modules/@serialport/bindings/lib/linux.js:2:36)
    at Module._compile (internal/modules/cjs/loader.js:1145:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1166:10)
    at Module.load (internal/modules/cjs/loader.js:981:32)
    at Module._load (internal/modules/cjs/loader.js:881:14)
    at Function.Module._load (electron/js2c/asar.js:779:28)
    at Module.require (internal/modules/cjs/loader.js:1023:19)
(node:1726) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
Checking for update
Update for version 1.0.2 is not available (latest version: 1.0.2, downgrade is disallowed).

What should I Do ?

**Comment by massiveradiation** [comment]
I'm getting the same error, did you ever resolve this?
Thanks
